### ISSUE TITLE
Arm64 binaries

### ISSUE THREAD

**Issue by frozenbonito** [makiuchi-d/arelo#2]
I really like this project.
Thank you for the development and continued maintenance.

It would be great to if binaries are provided for arm64 in GitHub Releases to make Go lang uncecessary for installation.

**Comment by makiuchi-d** [comment]
did it: [v1.10.2](/makiuchi-d/arelo/releases/tag/v1.10.2)

**Comment by frozenbonito** [comment]
Thank you!
